# Generated by Django 3.1.3 on 2020-12-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='店铺ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='店铺名')),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='店铺负责人')),
                ('manager_id', models.IntegerField(blank=True, null=True, verbose_name='店铺负责人ID')),
                ('center', models.CharField(max_length=100, verbose_name='渠道中心')),
                ('center_id', models.IntegerField(verbose_name='渠道中心ID')),
                ('platform', models.CharField(max_length=45, verbose_name='平台')),
                ('market', models.CharField(max_length=200, null=True, verbose_name='站点')),
                ('market_id', models.IntegerField(null=True, verbose_name='站点ID')),
                ('status', models.SmallIntegerField(choices=[(0, '关闭弃号'), (1, '正常可售'), (2, '注册中'), (3, '暂时关闭'), (4, '注册失败'), (5, '假期模式')], null=True, verbose_name='状态')),
                ('last_download_time', models.DateTimeField(blank=True, null=True, verbose_name='上次抓单时间')),
            ],
            options={
                'verbose_name': '店铺表',
                'verbose_name_plural': '店铺表',
                'db_table': 'oms_store',
                'managed': False,
            },
        ),
    ]
